name: Publish NuGet Package with Dynamic Version

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # lub wersja, której używasz

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dynamic version
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "Using version $VERSION"
          dotnet build --configuration Release -p:Version=$VERSION --no-restore

      - name: Pack with dynamic version
        run: |
          VERSION="1.0.${{ github.run_number }}"
          dotnet pack --configuration Release -p:Version=$VERSION --no-build

      - name: Push package to GitHub Packages
        run: dotnet nuget push "bin/Release/*.nupkg" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}